name: minigames
version: '1.0-SNAPSHOT'
main: cz.misakplak.minigames.Minigames
api-version: '1.21'
authors: [ misakplak ]
description: just a mod

commands:

  rebirth:
    description: a minigame to progress with rebirths
    usage: /rebirth

  rebirthreset:
    description: reset your rebirth levels
    usage: /rebirthreset
